// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnetelqsdbiacotgfxib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZXRlbHFzZGJpYWNvdGdmeGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTY2MTYsImV4cCI6MjA1NzUzMjYxNn0.Qb625WPK93DGcSyz4YJnG7TwWkrI-hTChAfXTdwrMPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);